### ISSUE TITLE
In list view start data it's not correct

### ISSUE THREAD

**Issue by anton01** [btactic/zimbra-catala#3]
Hello my version of Zimbra it's 8.6 patch 6.

When you are in List View the start data it's wrong (in start data doesn't appear right data),

for example:
should be appear: 11/02/20016, 11:00
but appear: 011ort:11:00

**Comment by adriangibanelbtactic** [comment]
@anton01 Given that you say that https://github.com/btactic/zimbra-catala/commit/e0c36655e09fcf88fbf9a2932f368596d9895e81 did not solve your problem...

Can you please explain step by step from login page how to reproduce the bug?
We might have misunderstood you.

Or... you can try to do a _zmcontrol restart_ as zimbra user and _ctrl+f5_ on your Internet browser just in case you are getting an old cache.

Thank you.

**Comment by anton01** [comment]
Hi,sorry, you are right.
Was problem of web browser cache.

After to clean cache, all work well.

Thanks a lot for your effort
Kind regards.
