### ISSUE TITLE
Zimbra 8.7 y rutas

### ISSUE THREAD

**Issue by rmontagud** [btactic/zimbra-catala#7]
Con Zimbra 8.7 han cambiado las rutas y de muchos binarios, entre ellos el de native2ascii, también si instalamos por nuestra cuenta los diccionarios han cambiado las rutas de aspell.
Tampoco entiendo el por que el uso de wildcards en el deploy cuando zimbra siempre hace un enlace simbólico /opt/zimbra/jetty/ a la versión correcta

       NATIVE2ASCII="/opt/zimbra/common/lib/jvm/java/bin/native2ascii"
       DESTDIR="/opt/zimbra/jetty/webapps/zimbra/WEB-INF/classes/messages"
       DESTDIRADMIN="/opt/zimbra/jetty/webapps/zimbraAdmin/WEB-INF/classes/messages"
       DESTDIRKEYS="/opt/zimbra/jetty/webapps/zimbra/WEB-INF/classes/keys"
       DESTDIRADMINKEYS="/opt/zimbra/jetty/webapps/zimbraAdmin/WEB-INF/classes/keys"

**Comment by adriangibanelbtactic** [comment]
Hello Rafael,

  I invite you to open a pull request with one commit for each one of your concerns:

* Remove asterisks from paths where they are not needed.
* Update dynamically the different paths depending on the Zimbra version found

Thank you.
